name: build-docs-workflow
on:
    push:
       branches:
            - master
jobs:
    build-docs:
        name: "Build Sphinx docs"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.7']
        steps:
            - name: Checkout Pilot2 repo
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64

            - name: Pip install
              run: pip install sphinx

            - name: Check sphinx version
              run: python -c "import sphinx;print(sphinx.__version__)"

            - name: Trigger panda-docs webhook
              env:
                READDOCS_TOKEN: ${{ secrets.READDOCS_TOKEN }}
                READDOCS_HOOK: ${{ secrets.READDOCS_HOOK }}
              run: curl -X POST -d "token=$READDOCS_TOKEN" $READDOCS_HOOK

